SLOT_REEL_LENGTH = 10

MASTERY_SCROLL_1_NAME = "mastery_scroll_1"
MASTERY_SCROLL_2_NAME = "mastery_scroll_2"
MASTERY_SCROLL_3_NAME = "mastery_scroll_3"
MASTERY_SCROLL_4_NAME = "mastery_scroll_4"
MASTERY_SCROLL_5_NAME = "mastery_scroll_5"
MASTERY_SCROLL_6_NAME = "mastery_scroll_6"
MASTERY_SCROLL_7_NAME = "mastery_scroll_7"
MASTERY_SCROLL_8_NAME = "mastery_scroll_8"
MASTERY_SCROLL_9_NAME = "mastery_scroll_9"
MASTERY_SCROLL_10_NAME = "mastery_scroll_10"

ACCOUNT_TIER_0_ID = "account_tier_0"
ACCOUNT_TIER_1_ID = "account_tier_1"
ACCOUNT_TIER_2_ID = "account_tier_2"
ACCOUNT_TIER_3_ID = "account_tier_3"
ACCOUNT_TIER_4_ID = "account_tier_4"
ACCOUNT_TIER_5_ID = "account_tier_5"
ACCOUNT_TIER_6_ID = "account_tier_6"

ACCOUNT_TIER_0_LABEL = "Free"
ACCOUNT_TIER_1_LABEL = "Plus"
ACCOUNT_TIER_2_LABEL = "Pro"
ACCOUNT_TIER_3_LABEL = "Enterprise"
ACCOUNT_TIER_4_LABEL = "Premium"
ACCOUNT_TIER_5_LABEL = "Luxurious"
ACCOUNT_TIER_6_LABEL = "Jewish"

ACCOUNT_TIER_0_TOKEN_PRICE = 0
ACCOUNT_TIER_1_TOKEN_PRICE = 10
ACCOUNT_TIER_2_TOKEN_PRICE = 25
ACCOUNT_TIER_3_TOKEN_PRICE = 100
ACCOUNT_TIER_4_TOKEN_PRICE = 1000
ACCOUNT_TIER_5_TOKEN_PRICE = 10000
ACCOUNT_TIER_6_TOKEN_PRICE = 67000
